app:
    resource: '@AppBundle/Controller/'
    type: annotation


picture:
    type:     rest
    resource: AppBundle\Controller\PictureController


album:
    type:     rest
    resource: AppBundle\Controller\AlbumController



